version: "2"
run:
  tests: true
  timeout: 5m
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  enable:
    - misspell
    - revive
    - shadow
linters-settings:
  errcheck:
    check-blank: true
  govet:
    enable:
      - shadow
  gofmt:
    simplify: true
  revive:
    confidence: 0.8
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
  exclude-dirs:
    - vendor
    - .idea