project_name: cobrak

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: cobrak
    main: ./main.go
    binary: cobrak
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: default
    format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE
      - CONFIGURATION.md

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
  algorithm: sha256

release:
  draft: false
  prerelease: auto
  name_template: 'Release {{.Version}}'
  header: |
    ## cobrak {{.Version}}

    ### Features & Improvements

  footer: |
    ## Installation

    ### Using Homebrew
    ```bash
    brew tap marcgeld/cobrak
    brew install cobrak
    ```

    ### Manual Installation
    Download the appropriate binary for your platform from the assets below.

    ### Docker
    ```bash
    docker run marcgeld/cobrak:{{.Version}} --help
    ```

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

brews:
  - tap:
      owner: marcgeld
      name: homebrew-cobrak
    folder: Formula
    homepage: https://github.com/marcgeld/cobrak
    description: Kubernetes cluster analysis CLI
    license: MIT
    skip_upload: true

dockers:
  - image_templates:
      - 'marcgeld/cobrak:latest'
      - 'marcgeld/cobrak:{{ .Tag }}'
      - 'marcgeld/cobrak:v{{ .Major }}.{{ .Minor }}'
    build_flag_templates:
      - '--pull'
      - '--label=org.opencontainers.image.created={{.Date}}'
      - '--label=org.opencontainers.image.revision={{.FullCommit}}'
      - '--label=org.opencontainers.image.version={{.Version}}'
    skip_push: true

signs:
  - artifacts: checksum
    cmd: cosign
    args:
      - 'sign-blob'
      - '--key=cosign.key'
      - '${artifact}'
    output: true
    artifacts: all

announce:
  slack:
    enabled: false
  twitter:
    enabled: false

